<?php
	 require_once('../../config.php');
	 global $PAGE,$DB,$USER;
	if($_POST['request'] == 'showgrade' && $_POST['cmid'] != null && $_POST['option'] != null){


		$sql='update {block_assessment_information} set gradevisible= '.$_POST['option'].' where itemid='.$_POST['cmid'];
		 $return = $DB->execute($sql);
		 echo $return;

	}
	if($_POST['request'] == 'regulartime' && $_POST['course'] != ""){

	   	$sql = "select section from {course_sections} where (name='Generated by Assessment Information block' OR section = 52) and course=".$_POST['course'];
	   	$courseid = $_POST['course'];
		$sql1 = "
select * 
from {course_sections} 
where course = $courseid 
and (sequence = '666' or sequence like '666,%' or sequence like '%,666,%' or sequence like '%,666' or section = 52)
";

		$result=$DB->get_record_sql($sql);

		if(isset($result) && isset($result->section) && $result->section != ""){
			echo $result->section;
		}
	}


?>
